duckdb:
  target: standalone

  outputs:
    standalone:
      type: duckdb
      path: coronavirus.duckdb
      schema: italy
      extensions:
        - spatial

    testing:
      type: duckdb
      extensions:
        - spatial
