version: 2

sources:
  - name: pcm-dpc
    config:
      external_location: 'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-{name}/dpc-covid19-ita-{name}.csv'
    tables:
      - name: andamento-nazionale
      - name: regioni
      - name: province

  - name: openpolis
    config:
      external_location: st_read('https://raw.githubusercontent.com/openpolis/geojson-italy/main/geojson/limits_IT_{name}.geojson')
    tables:
      - name: regions
      - name: provinces
